// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PedidosAPI.Infrastructure.Data;

#nullable disable

namespace PedidosAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622193110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PedidosAPI.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10a0dd53-3759-4e51-a943-aee9194fca72"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClienteNome = "Ana Silva",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-0001",
                            Status = 0,
                            ValorTotal = 250.00m
                        },
                        new
                        {
                            Id = new Guid("ac2ec4fc-cd6d-4952-bc8c-20e34314a3db"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClienteNome = "Carlos Souza",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-0002",
                            Status = 2,
                            ValorTotal = 1340.00m
                        },
                        new
                        {
                            Id = new Guid("6df72602-3a6e-4fb7-a597-6cd737c664a9"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClienteNome = "Fernanda Lima",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-0003",
                            Status = 4,
                            ValorTotal = 89.90m
                        },
                        new
                        {
                            Id = new Guid("b1435725-ee0c-494c-af0e-8fe917b331b8"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClienteNome = "Ricardo Mendes",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-0004",
                            Status = 5,
                            ValorTotal = 499.00m
                        },
                        new
                        {
                            Id = new Guid("e4677994-bb91-4d4e-a00a-62d7425df5ea"),
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClienteNome = "Juliana Costa",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-0005",
                            Status = 6,
                            ValorTotal = 720.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
